---
language: node_js
node_js:
  - "8.2.1"

sudo: false

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test
