---
language: node_js
node_js:
  - "8.2.1"

sudo: false

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm

before_install:
  - curl -o- -L https:// pkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm config set spin false

install:
  - npm install

script:
  - npm test
