dist: trusty
language: node_js
node_js:
  - "6"

sudo: false

addons:
  chrome: stable
  hosts: 
   - app.bsc.local

cache:
  directories:
     - $HOME/.npm
     - node_modules

install:
  - npm install

script:
  - npm test
